### ISSUE TITLE
Language key issue

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-onlineusers#1]
Hi!

Change it to all files:
ex.:
Yii::t('**onlineusers**.views_OnlineUsers', '<strong>Online</strong> Users');
to
Yii::t('**OnlineUsersModule**.views_OnlineUsers', '<strong>Online</strong> Users');

**Comment by WASasquatch** [comment]
Is that the language issues I've been having? Thanks.

**Comment by Vatarus** [comment]
I decided to make Russian localization and encountered an error.
![onlineusers](https://cloud.githubusercontent.com/assets/3394915/7552926/6a42e342-f70e-11e4-8730-4ab6bba8b1ff.png)

Change the file extension to zip

**Comment by Vatarus** [comment]
screenshots
![onlain01](https://cloud.githubusercontent.com/assets/3394915/7552953/df59d938-f70e-11e4-88f1-020a31fb4437.png)
![online02](https://cloud.githubusercontent.com/assets/3394915/7552956/e4cb1198-f70e-11e4-9bd7-6dba2d69d384.png)

**Comment by WASasquatch** [comment]
I don't know what you mean about changing to zip. I have updated the language keys though.
